---
- name: Simple playbook for localhost with user addition, curl, git, and apache2
  hosts: localhost
  become: true  # Run tasks with sudo
  tasks:
    - name: Add ansible_user
      user:
        name: ansible_user
        state: present
        create_home: yes
        shell: /bin/bash

    - name: Install curl
      package:
        name: curl
        state: present

    - name: Install git
      package:
        name: git
        state: present

    - name: Install apache2
      package:
        name: apache2
        state: present

    - name: Install net-tools
      package:
        name: net-tools
        state: present

    - name: Ensure apache2 is started and enabled on boot
      service:
        name: apache2
        state: started
        enabled: yes

    - name: Create a file in the home directory
      copy:
        content: "Hello, Ansible!"
        dest: ~/hello_ansible.txt
